# Written by: Christopher Gholmieh
# Fonts:
[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
