#! /bin/sh

# Written by: Christopher Gholmieh
# Processes:
pgrep -x sxhkd > /dev/null | sxhkd &
picom &
dunst &
polybar main &

feh --bg-fill $HOME/.config/wallpapers/mountain-peak.jpg &

# Workspaces:
bspc monitor -d I II III IV V

# Configuration:
bspc config focus_follows_pointer	true

bspc config border_width         	2
bspc config window_gap          	12

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
